const DB_NAME='book-guide-v4';const STORE='books';const DEMO=[{id:'d1',title:'اسرق مثل فنان',author:'أوستن كليون',location:'H8'},{id:'d2',title:'الفوائد',author:'ابن قيم الجوزية',location:'K3'},{id:'d3',title:'رسائل من الصحابة',author:'أدهم الشرقاوي',location:'B6'},{id:'d4',title:'رسائل إلى الشباب',author:'أدهم الشرقاوي',location:'C2'},{id:'d5',title:'روضة المحبين',author:'ابن القيم',location:'A7'}];const LETTERS=['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي'];const $=s=>document.querySelector(s);const view=$('#appView');let books=[];let db;
function norm(v=''){return String(v).toLocaleLowerCase('ar').normalize('NFKC').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/\s+/g,' ').trim()}
function firstWord(title){let words=norm(title).split(' ').filter(Boolean);if(words[0]==='ال'&&words[1])words.shift();if(words[0]?.startsWith('ال')&&words[0].length>2)words[0]=words[0].slice(2);return words[0]||'غير مصنف'}
function firstLetter(title){let w=firstWord(title);return LETTERS.includes(w[0])?w[0]:'#'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openDb(){return new Promise((res,rej)=>{let r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function allBooks(){return new Promise((res,rej)=>{let r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function putBooks(values){return new Promise((res,rej)=>{let t=db.transaction(STORE,'readwrite'),s=t.objectStore(STORE);s.clear();values.forEach(b=>s.put(b));t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function field(row,names){let entries=Object.entries(row||{});let found=entries.find(([k])=>names.some(n=>norm(k)===norm(n)||norm(k).includes(norm(n))));return found?.[1]??''}
function mapRows(rows){return rows.map((r,i)=>({id:`book-${i}-${crypto.randomUUID()}`,title:String(field(r,['اسم الكتاب','الكتاب','العنوان','title','book','name'])).trim(),author:String(field(r,['اسم المؤلف','المؤلف','author','writer'])).trim(),location:String(field(r,['المكان','مكان الكتاب','الرف','shelf','location','place'])).trim()})).filter(b=>b.title)}
function setCount(){let active=books.length;$('#bookCount').textContent=`${active} كتاب`;$('#libraryStats').textContent=`${active} كتاب محمل`}
function header(title,back){return `<div class="section-head">${back?'<button class="back-button" id="back">‹</button>':''}<h2>${esc(title)}</h2></div>`}
function home(){view.innerHTML=`<div class="home-view"><div><h2>الوصول لمكان الكتاب</h2><p>اختار الاسم من الحروف، بدون كتابة وبدون زحمة.</p></div><button class="main-button" id="startBooks">اسم الكتاب<small>الحروف ← البداية ← الكتاب ← المكان</small></button></div>`;$('#startBooks').onclick=letters}
function letters(){let groups={};books.forEach(b=>{let l=firstLetter(b.title);groups[l]=(groups[l]||0)+1});let html=Object.entries(groups).filter(([l])=>l!=='#').sort((a,b)=>LETTERS.indexOf(a[0])-LETTERS.indexOf(b[0])).map(([l,n])=>`<button class="letter-button" data-letter="${l}">${l}<small>${n} كتاب</small></button>`).join('');if(groups['#'])html+=`<button class="letter-button" data-letter="#">#<small>${groups['#']} كتاب</small></button>`;view.innerHTML=header('اختر أول حرف')+`<p class="path">اسم الكتاب</p><div class="letter-grid">${html||'<div class="empty-state">ارفع ملف الكتب من الإعدادات أولًا.</div>'}</div>`;view.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>words(b.dataset.letter))}
function words(letter){let group=books.filter(b=>firstLetter(b.title)===letter),map=new Map();group.forEach(b=>{let w=firstWord(b.title);map.set(w,(map.get(w)||0)+1)});let html=[...map].sort((a,b)=>a[0].localeCompare(b[0],'ar')).map(([w,n])=>`<button class="word-button" data-word="${esc(w)}"><span>${esc(w)}</span><small>${n} ${n===1?'كتاب':'كتب'} ›</small></button>`).join('');view.innerHTML=header(`البداية بحرف «${letter}»`,true)+`<p class="path">اسم الكتاب ← ${letter}</p><div class="word-list">${html}</div>`;$('#back').onclick=letters;view.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>bookList(letter,b.dataset.word))}
function bookList(letter,word){let group=books.filter(b=>firstLetter(b.title)===letter&&firstWord(b.title)===word).sort((a,b)=>norm(a.title).localeCompare(norm(b.title),'ar'));let html=group.map(b=>`<button class="book-button" data-id="${b.id}"><strong>${esc(b.title)}</strong><small>${esc(b.author||'المؤلف غير مسجل')}</small></button>`).join('');view.innerHTML=header(`كتب تبدأ بـ «${word}»`,true)+`<p class="path">اسم الكتاب ← ${letter} ← ${word}</p><div class="book-list">${html}</div>`;$('#back').onclick=()=>words(letter);view.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>showBook(b.dataset.id))}
function showBook(id){let b=books.find(x=>x.id===id);if(!b)return;view.innerHTML=header('بيانات الكتاب',true)+`<p class="path">اسم الكتاب ← ${firstLetter(b.title)} ← ${firstWord(b.title)}</p><div class="result-card"><div class="label">اسم الكتاب</div><h2>${esc(b.title)}</h2><div class="author">${esc(b.author||'المؤلف غير مسجل')}</div><div class="location-label">مكان الكتاب</div><div class="location">${esc(b.location||'—')}</div><div class="result-note">تم الوصول من بيانات المكتبة المحلية</div></div><button class="again-button" id="again">العودة إلى الحروف</button>`;$('#back').onclick=()=>bookList(firstLetter(b.title),firstWord(b.title));$('#again').onclick=letters}
async function importSheet(file){let buffer=await file.arrayBuffer(),wb=XLSX.read(buffer,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}),next=mapRows(rows);if(!next.length)throw Error('لم أجد عمود اسم الكتاب');books=next;await putBooks(books);setCount();$('#sheetInfo').textContent=`تم تحميل ${books.length} كتاب من ${file.name}`;letters()}
function wire(){home();$('#settingsButton').onclick=()=>$('#settingsDialog').showModal();$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#settingsDialog').onclick=e=>{if(e.target===$('#settingsDialog'))$('#settingsDialog').close()};$('#sheetFile').onchange=async e=>{try{await importSheet(e.target.files[0])}catch(err){$('#sheetInfo').textContent=`تعذر التحميل: ${err.message}`}e.target.value=''};$('#resetDemo').onclick=async()=>{books=DEMO.map(b=>({...b}));await putBooks(books);setCount();$('#sheetInfo').textContent='تمت استعادة نماذج التجربة';home()}}
async function init(){await openDb();books=await allBooks();if(!books.length){books=DEMO.map(b=>({...b}));await putBooks(books)}setCount();wire()}init();
